# Generated by Django 3.1.5 on 2021-01-20 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myImageBank', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageProduit',
            new_name='ImageProduct',
        ),
    ]
