# Generated by Django 3.1.5 on 2021-01-25 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myImageBank', '0002_auto_20210120_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageproduct',
            options={'ordering': ('url',)},
        ),
        migrations.RemoveField(
            model_name='imageproduct',
            name='tigID',
        ),
    ]
