# Generated by Django 3.1.5 on 2021-01-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myImageBank', '0003_auto_20210125_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageproduct',
            options={'ordering': ('url', 'metadata')},
        ),
        migrations.AddField(
            model_name='imageproduct',
            name='metadata',
            field=models.TextField(default=[]),
        ),
    ]
