# Generated by Django 3.1.5 on 2021-01-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myImageBank', '0004_auto_20210125_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProductMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('keyword', models.TextField(default='default')),
                ('idList', models.IntegerField(default='-1')),
            ],
            options={
                'ordering': ('keyword',),
            },
        ),
        migrations.AlterModelOptions(
            name='imageproduct',
            options={'ordering': ('url',)},
        ),
    ]
