version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./docker/postegres/db:/var/lib/postgresql/data/

  web: 
    build: ./docker/python
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8082:8000"
    volumes:
      - ./mySearchEngine:/opt/www/mySearchEngine
      - /tmp/app/mysqld:/run/mysqld
    depends_on:
      - db